In [2]:
a=[1,2,3,4]
b=[2,3,4,5]

In [5]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab    

[2, 6, 12, 20]

In [6]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b
#numpy işlemleri daha hızlı ve güzel yapmamızı sağlıyor verileri daha performanslı tutar

array([ 2,  6, 12, 20])

In [7]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14,2,8,11],dtype="float32")

array([ 3.14,  2.  ,  8.  , 11.  ], dtype=float32)

In [14]:
#doğrusal dizi oluşturmaya yarar
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.random.normal(10,4,(3,4))

array([[ 1.68608475, 14.46643199,  7.13527378,  6.8916045 ],
       [12.06286856,  7.11443151,  4.29971766,  6.92185356],
       [ 2.24488463, 11.87024982,  7.40370391,  6.80700418]])

In [16]:
np.random.randint(0,10,(3,3))

array([[8, 2, 9],
       [8, 0, 6],
       [9, 9, 1]])

In [17]:
#ndim=boyut sayısı
#shape=boyut bilgisi
#size=toplam eleman sayısı
#dtype=arrayin veri tipi

In [19]:
a=np.random.randint(10,size=10)
a

array([5, 9, 4, 3, 6, 7, 2, 7, 3, 8])

In [20]:
a.ndim

1

In [22]:
a.shape

(10,)

In [24]:
a.size

10

In [25]:
a.dtype

dtype('int64')

In [26]:
b=np.random.randint(10,size=(3,5))
b

array([[4, 4, 8, 3, 8],
       [1, 0, 9, 7, 5],
       [4, 5, 2, 5, 1]])

In [27]:
b.ndim

2

In [28]:
b.shape

(3, 5)

In [31]:
b.dtype

dtype('int64')

In [32]:
b.size

15

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b=np.arange(1,10).reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b.ndim
#artık bir matris olacağı için boyutu 2 olmuştur

2

In [44]:
#array birleştirme işlemleri

In [45]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [47]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [48]:
z=np.array([7,8,9])

In [49]:
#iki boyut üzerine array i birleştirmek

In [50]:
a=np.array([[1,2,3],
           [4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([a,a])
#satır bazında bir birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
#array ayırma

In [57]:
x=np.array([1,2,3,4,5,6,7,8,9])

In [59]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [61]:
a,b,c=np.split(x,[3,5])

In [63]:
a

array([1, 2, 3])

In [64]:
b

array([4, 5])

In [65]:
c

array([6, 7, 8, 9])

In [71]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
q,w=np.vsplit(m,[2])

In [77]:
q

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [79]:
w

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
sag,sol=np.hsplit(m,[2])

In [87]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [88]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [90]:
#sorting sıralama işlemleri

In [91]:
v=np.array([2,3,1,4,5])
v

array([2, 3, 1, 4, 5])

In [93]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [94]:
v

array([1, 2, 3, 4, 5])

In [95]:
#iki boyutlu array sıralama

In [99]:
m=np.random.normal(20,5,(3,3))
m

array([[24.59143666, 20.65978651, 14.71353533],
       [21.77994706, 24.23060774, 16.0965994 ],
       [23.48723211, 15.30101953,  8.89801383]])

In [100]:
np.sort(m,axis=0)

array([[21.77994706, 15.30101953,  8.89801383],
       [23.48723211, 20.65978651, 14.71353533],
       [24.59143666, 24.23060774, 16.0965994 ]])

In [101]:
np.sort(m,axis=1)

array([[14.71353533, 20.65978651, 24.59143666],
       [16.0965994 , 21.77994706, 24.23060774],
       [ 8.89801383, 15.30101953, 23.48723211]])

In [104]:
#index ile elemanlara erişmek 

In [108]:
a=np.random.randint(10,size=10)
a

array([2, 0, 4, 7, 7, 3, 2, 5, 8, 7])

In [109]:
a[0]

2

In [110]:
a[-1]

7

In [111]:
a[0]=100
a

array([100,   0,   4,   7,   7,   3,   2,   5,   8,   7])

In [112]:
m=np.random.randint(10,size=(3,5))
m

array([[2, 3, 0, 5, 9],
       [6, 6, 8, 0, 7],
       [7, 7, 9, 3, 1]])

In [113]:
m[0,0]

2

In [114]:
#alt küme islemleri

In [116]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [118]:
a[2::3]
#ardışıklı seçim

array([22, 25, 28])

In [119]:
#iki boyutlu slice işlemleri

In [120]:
m=np.random.randint(10,size=(5,5))
m

array([[9, 4, 6, 8, 5],
       [7, 2, 7, 6, 6],
       [5, 7, 6, 2, 2],
       [9, 4, 8, 1, 7],
       [7, 1, 9, 5, 5]])

In [124]:
m[:,0]

array([9, 7, 5, 9, 7])

In [125]:
m[0,:]

array([9, 4, 6, 8, 5])

In [126]:
m[1,:]

array([7, 2, 7, 6, 6])

In [127]:
m[0:2,0:3]

array([[9, 4, 6],
       [7, 2, 7]])

In [128]:
#alt küme üzerinde işlem yaparken üst kümede değişklik olmasını istemiyorsak copy methodunu kullanmalıyız

In [129]:
m=np.random.randint(10,size=(5,5))
m

array([[9, 5, 4, 2, 9],
       [4, 3, 4, 1, 1],
       [9, 9, 8, 0, 1],
       [8, 9, 0, 9, 1],
       [7, 9, 3, 4, 5]])

In [130]:
alt_b=m[:3,:4].copy()
alt_b

array([[9, 5, 4, 2],
       [4, 3, 4, 1],
       [9, 9, 8, 0]])

In [131]:
alt_b[0,0]=999999

In [132]:
m

array([[9, 5, 4, 2, 9],
       [4, 3, 4, 1, 1],
       [9, 9, 8, 0, 1],
       [8, 9, 0, 9, 1],
       [7, 9, 3, 4, 5]])

In [133]:
#fancy index ile elemanlara erişmek

In [134]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [135]:
al_getir=[1,3,5]

In [136]:
v[al_getir]
#bu fancy indextir

array([ 3,  9, 15])

In [137]:
#boyutta fancy

In [140]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
satir=np.array([0,1])
sutun=np.array([1,0])

In [142]:
m[satir,sutun]

array([1, 3])

In [143]:
#koşullu eleman işlemleri

In [145]:
v=np.array([1,2,3,4,5])

In [146]:
v>3

array([False, False, False,  True,  True])

In [147]:
v[v<3]

array([1, 2])

In [148]:
v[v!=4]

array([1, 2, 3, 5])

In [150]:
v*5

array([ 5, 10, 15, 20, 25])

In [151]:
v/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [152]:
#matematiksel işlemler

In [153]:
v-1

array([0, 1, 2, 3, 4])

In [154]:
v%3

array([1, 2, 0, 1, 2])

In [155]:
#ufunc

In [156]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [157]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [158]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [159]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [160]:
np.power(v,2)

array([ 1,  4,  9, 16, 25])

In [161]:
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [163]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [164]:
np.absolute(np.array([-3]))

array([3])

In [165]:
np.sin(259)

0.9835931839466808

In [166]:
np.cos(121)

-0.0486636092001539

In [167]:
#logaritma alma
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [168]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [169]:
?np
#numpy'ın ana dökümantasyonudur

Type:        module
String form: <module 'numpy' from '/Users/mehmetakifkiraz/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::



In [170]:
#numpy iki bilinmeyenli denklem çözümü

In [171]:
#5 x0 + x1 = 12
# x0 + 3 * x1 = 10

In [173]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
a

array([[5, 1],
       [1, 3]])

In [174]:
b

array([12, 10])

In [176]:
#şimdi lineercebir işlemleri için özelleştirilmiş methodları kullanıyorum
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [177]:
#pandas bölümüne giriş 

In [178]:
import pandas as pd
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [187]:
seri=pd.Series([99,22,3,4,5])
seri

0    99
1    22
2     3
3     4
4     5
dtype: int64

In [181]:
type(seri)

pandas.core.series.Series

In [182]:
#serinin indeks bilgilerine erişiyoruz
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [184]:
seri.dtype

dtype('int64')

In [185]:
seri.size

5

In [186]:
#index numaraları olmadan sadece bir array formunda erişmek için values kullanılır
seri.values

array([99, 22,  3,  4,  5])